export const WEATHER_CITY_DOWNLOAD = "WEATHER_DOWNLOAD";
export const WEATHER_CITY_DOWNLOAD_START = "WEATHER_DOWNLOAD_START";
export const WEATHER_CITY_DOWNLOAD_SUCCECED = "WEATHER_DOWNLOAD_SUCCECED";
export const WEATHER_CITY_DOWNLOAD_FAILED = "WEATHER_DOWNLOAD_FAILED";

export const SUBSCRIBE_WEATHER_CITY = "SUBSCRIBE_WEATHER_CITY";
export const UNSUBSCRIBE_WEATHER_CITY = "UNSUBSCRIBE_WEATHER_CITY"

export const FETCH_WEATHER_CITY = "FETCH_WEATHER_CITY";
export const FETCH_WEATHER_CITY_START = "FETCH_WEATHER_CITY_START";
export const FETCH_WEATHER_CITY_SUCCECED = "FETCH_WEATHER_CITY_SUCCECED";

export const SELECT_CITY ="SELECT_CITY";
export const DELETE_CITY = "DELETE_CITY";
export const REFRESH_CITY_START = "REFRESH_CITY_START";